# Generated by Django 4.2.5 on 2023-10-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name="CoffeeBean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                ("roast_level", models.CharField(max_length=50)),
                ("flavor_notes", models.TextField()),
                ("stock_quantity", models.IntegerField()),
            ],
        ),
    ]
