# Generated by Django 4.2.5 on 2023-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeebean",
            name="flavor_notes",
            field=models.TextField(verbose_name="Flavor Notes"),
        ),
        migrations.AlterField(
            model_name="coffeebean",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="coffeebean",
            name="origin",
            field=models.CharField(max_length=100, verbose_name="Origin"),
        ),
        migrations.AlterField(
            model_name="coffeebean",
            name="roast_level",
            field=models.CharField(max_length=50, verbose_name="Roast Level"),
        ),
        migrations.AlterField(
            model_name="coffeebean",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Stock Quantity"),
        ),
    ]
