# Generated by Django 5.2 on 2025-08-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name="CoffeeBean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("origin", models.CharField(max_length=100, verbose_name="Origin")),
                (
                    "roast_level",
                    models.CharField(max_length=50, verbose_name="Roast Level"),
                ),
                ("flavor_notes", models.TextField(verbose_name="Flavor Notes")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stock Quantity"
                    ),
                ),
            ],
        ),
    ]
